// packages/react/src/index.tsx
import React, {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useSyncExternalStore
} from "react";
import {
  createModalController,
  createModalManager,
  type ModalBehaviorOptions,
  type ModalManager
} from "@modal-kit/core";
import {
  modalClassNames,
  themeClassNames,
  type ModalTheme
} from "@modal-kit/ui";

const ModalContext = createContext<ModalManager | null>(null);

export interface ModalProviderProps {
  children: React.ReactNode;
  manager?: ModalManager;
}

export const ModalProvider = ({ children, manager }: ModalProviderProps) => {
  const value = useMemo(() => manager ?? createModalManager(), [manager]);
  return <ModalContext.Provider value={value}>{children}</ModalContext.Provider>;
};

const useManager = (): ModalManager => {
  const context = useContext(ModalContext);
  if (!context) {
    throw new Error("ModalProvider is missing in the React tree");
  }
  return context;
};

export const useModal = (id: string) => {
  const manager = useManager();
  const isOpen = useSyncExternalStore(
    (listener) => manager.subscribe(listener),
    () => manager.isOpen(id)
  );

  return {
    isOpen,
    open: () => manager.open(id),
    close: () => manager.close(id)
  };
};

export type ElementOrGetter = HTMLElement | (() => HTMLElement | null) | null;

export interface UseModalControllerOptions extends ModalBehaviorOptions {
  overlay?: ElementOrGetter;
  container?: ElementOrGetter;
  initialFocus?: HTMLElement | (() => HTMLElement | null) | null;
  restoreFocusTarget?: HTMLElement | (() => HTMLElement | null) | null;
}

const resolveElement = (target?: ElementOrGetter): HTMLElement | null => {
  if (!target) {
    return null;
  }
  return typeof target === "function" ? target() : target;
};

export const useModalController = (id: string, options: UseModalControllerOptions) => {
  const manager = useManager();

  useEffect(() => {
    const container = resolveElement(options.container);
    const overlay = resolveElement(options.overlay);
    if (!container) {
      return;
    }

    const controller = createModalController(id, manager, {
      container,
      overlay,
      closeOnEsc: options.closeOnEsc,
      closeOnOverlay: options.closeOnOverlay,
      trapFocus: options.trapFocus,
      lockScroll: options.lockScroll,
      restoreFocus: options.restoreFocus,
      initialFocus: options.initialFocus,
      restoreFocusTarget: options.restoreFocusTarget
    });

    return () => controller.destroy();
  }, [
    id,
    manager,
    options.container,
    options.overlay,
    options.closeOnEsc,
    options.closeOnOverlay,
    options.trapFocus,
    options.lockScroll,
    options.restoreFocus,
    options.initialFocus,
    options.restoreFocusTarget
  ]);
};

export type ConfirmVariant = "destructive" | "approve" | "info";
export type ConfirmPreset = "delete" | "approve";

export interface ConfirmModalProps extends ModalBehaviorOptions {
  id: string;
  title?: string;
  description?: string;
  details?: string;
  confirmLabel?: string;
  cancelLabel?: string;
  variant?: ConfirmVariant;
  preset?: ConfirmPreset;
  icon?: string;
  theme?: ModalTheme;
  onConfirm?: () => void;
  onCancel?: () => void;
}

export const ConfirmModal = ({
  id,
  title,
  description,
  details,
  confirmLabel = "Confirm",
  cancelLabel = "Cancel",
  variant = "approve",
  preset,
  icon,
  theme = "brutalist",
  onConfirm,
  onCancel,
  closeOnEsc,
  closeOnOverlay,
  trapFocus,
  lockScroll,
  restoreFocus
}: ConfirmModalProps) => {
  const { isOpen, close } = useModal(id);
  const overlayRef = useRef<HTMLDivElement | null>(null);
  const panelRef = useRef<HTMLDivElement | null>(null);
  const confirmButtonRef = useRef<HTMLButtonElement | null>(null);

  useModalController(id, {
    overlay: () => overlayRef.current,
    container: () => panelRef.current,
    initialFocus: () => confirmButtonRef.current,
    closeOnEsc,
    closeOnOverlay,
    trapFocus,
    lockScroll,
    restoreFocus
  });

  if (!isOpen) {
    return null;
  }

  const presetDefaults =
    preset === "delete"
      ? {
          title: "Delete this item?",
          description: "This action cannot be undone.",
          confirmLabel: "Delete",
          cancelLabel: "Cancel",
          variant: "destructive" as ConfirmVariant,
          icon: "!"
        }
      : preset === "approve"
        ? {
            title: "Approve this change?",
            description: "It will be applied immediately.",
            confirmLabel: "Approve",
            cancelLabel: "Cancel",
            variant: "approve" as ConfirmVariant,
            icon: "+"
          }
        : null;

  const resolvedTitle = title ?? presetDefaults?.title ?? "Confirm action";
  const resolvedDescription = description ?? presetDefaults?.description;
  const resolvedConfirm = confirmLabel ?? presetDefaults?.confirmLabel ?? "Confirm";
  const resolvedCancel = cancelLabel ?? presetDefaults?.cancelLabel ?? "Cancel";
  const resolvedVariant = variant ?? presetDefaults?.variant ?? "approve";
  const resolvedIcon = icon ?? presetDefaults?.icon ?? "?";

  const handleConfirm = () => {
    onConfirm?.();
    close();
  };

  const handleCancel = () => {
    onCancel?.();
    close();
  };

  return (
    <div
      className={`${modalClassNames.root} ${themeClassNames[theme]} ${modalClassNames.confirmVariant}`}
      data-variant={resolvedVariant}
    >
      <div className={modalClassNames.overlay} ref={overlayRef}>
        <div
          className={modalClassNames.panel}
          ref={panelRef}
        >
          <div className={modalClassNames.header}>
            <div className={modalClassNames.icon}>{resolvedIcon}</div>
            <div className={modalClassNames.text}>
              <div className={modalClassNames.title}>{resolvedTitle}</div>
              {resolvedDescription ? (
                <div className={modalClassNames.description}>{resolvedDescription}</div>
              ) : null}
              {details ? <div className={modalClassNames.details}>{details}</div> : null}
            </div>
          </div>
          <div className={modalClassNames.actions}>
            <button
              className={`${modalClassNames.button} ${modalClassNames.cancelButton}`}
              type="button"
              onClick={handleCancel}
            >
              {resolvedCancel}
            </button>
            <button
              className={`${modalClassNames.button} ${modalClassNames.confirmButton}`}
              type="button"
              onClick={handleConfirm}
              ref={confirmButtonRef}
            >
              {resolvedConfirm}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

// packages/web-components/src/index.ts
import { LitElement, css, html } from "lit";
import { createRef, ref } from "lit/directives/ref.js";
import {
  createModalController,
  createModalManager,
  type ModalManager
} from "@modal-kit/core";
import { modalClassNames, themeClassNames } from "@modal-kit/ui";

export class ModalKitHost extends LitElement {
  static styles = css`
    :host {
      display: block;
    }
  `;

  private manager: ModalManager = createModalManager();

  open(id: string) {
    this.manager.open(id);
    this.requestUpdate();
  }

  close(id: string) {
    this.manager.close(id);
    this.requestUpdate();
  }

  isOpen(id: string) {
    return this.manager.isOpen(id);
  }

  render() {
    return html`<slot></slot>`;
  }
}

customElements.define("modal-kit-host", ModalKitHost);

export class ModalKitConfirm extends LitElement {
  static properties = {
    open: { type: Boolean, reflect: true },
    title: { type: String },
    description: { type: String },
    details: { type: String },
    confirmLabel: { type: String, attribute: "confirm-label" },
    cancelLabel: { type: String, attribute: "cancel-label" },
    variant: { type: String },
    preset: { type: String },
    icon: { type: String },
    theme: { type: String }
  };

  static styles = css`
    :host {
      display: contents;
    }
  `;

  createRenderRoot() {
    return this;
  }

  open = false;
  title = "";
  description = "";
  details = "";
  confirmLabel = "Confirm";
  cancelLabel = "Cancel";
  variant: "destructive" | "approve" | "info" = "approve";
  preset: "delete" | "approve" | "" = "";
  icon = "";
  theme:
    | "brutalist"
    | "retro"
    | "swiss"
    | "cyber"
    | "paper"
    | "glass"
    | "y2k"
    | "mono"
    | "bauhaus"
    | "noir"
    | "pastel"
    | "terminal"
    | "candy"
    | "nature"
    | "futurist"
    | "gothic" = "brutalist";

  private manager: ModalManager = createModalManager();
  private controller: ReturnType<typeof createModalController> | null = null;
  private panelRef = createRef<HTMLDivElement>();
  private overlayRef = createRef<HTMLDivElement>();
  private confirmButtonRef = createRef<HTMLButtonElement>();

  firstUpdated() {
    if (!this.panelRef.value) {
      return;
    }
    this.controller = createModalController("confirm", this.manager, {
      container: this.panelRef.value,
      overlay: this.overlayRef.value ?? undefined,
      initialFocus: () => this.confirmButtonRef.value ?? null
    });
  }

  disconnectedCallback() {
    this.controller?.destroy();
    super.disconnectedCallback();
  }

  updated(changed: Map<string, unknown>) {
    if (changed.has("open")) {
      if (this.open) {
        this.manager.open("confirm");
      } else {
        this.manager.close("confirm");
      }
    }
  }

  private handleCancel() {
    this.open = false;
    this.dispatchEvent(new CustomEvent("cancel"));
  }

  private handleConfirm() {
    this.open = false;
    this.dispatchEvent(new CustomEvent("confirm"));
  }

  render() {
    if (!this.open) {
      return null;
    }

    const preset = this.preset === "delete"
      ? {
          title: "Delete this item?",
          description: "This action cannot be undone.",
          confirmLabel: "Delete",
          cancelLabel: "Cancel",
          variant: "destructive" as const,
          icon: "!"
        }
      : this.preset === "approve"
        ? {
            title: "Approve this change?",
            description: "It will be applied immediately.",
            confirmLabel: "Approve",
            cancelLabel: "Cancel",
            variant: "approve" as const,
            icon: "+"
          }
        : null;

    const resolvedTitle = this.title || preset?.title || "Confirm action";
    const resolvedDescription = this.description || preset?.description || "";
    const resolvedConfirm = this.confirmLabel || preset?.confirmLabel || "Confirm";
    const resolvedCancel = this.cancelLabel || preset?.cancelLabel || "Cancel";
    const resolvedVariant = this.variant || preset?.variant || "approve";
    const resolvedIcon = this.icon || preset?.icon || "?";

    return html`
      <div
        class="${modalClassNames.root} ${themeClassNames[this.theme]} ${modalClassNames.confirmVariant}"
        data-variant=${resolvedVariant}
      >
        <div class=${modalClassNames.overlay} ${ref(this.overlayRef)}>
          <div
            class=${modalClassNames.panel}
            ${ref(this.panelRef)}
          >
            <div class=${modalClassNames.header}>
              <div class=${modalClassNames.icon}>${resolvedIcon}</div>
              <div class=${modalClassNames.text}>
                <div class=${modalClassNames.title}>${resolvedTitle}</div>
                ${resolvedDescription
                  ? html`<div class=${modalClassNames.description}>${resolvedDescription}</div>`
                  : null}
                ${this.details
                  ? html`<div class=${modalClassNames.details}>${this.details}</div>`
                  : null}
              </div>
            </div>
            <div class=${modalClassNames.actions}>
              <button
                class="${modalClassNames.button} ${modalClassNames.cancelButton}"
                type="button"
                @click=${this.handleCancel}
              >
                ${resolvedCancel}
              </button>
              <button
                class="${modalClassNames.button} ${modalClassNames.confirmButton}"
                type="button"
                @click=${this.handleConfirm}
                ${ref(this.confirmButtonRef)}
              >
                ${resolvedConfirm}
              </button>
            </div>
          </div>
        </div>
      </div>
    `;
  }
}

customElements.define("modal-kit-confirm", ModalKitConfirm);
